EbookManager.BackOffice/Controllers/AdminCatalogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using EbookManager.BackOffice.Models;
using EbookManager.CommonViewModels;
using EbookManager.Domain.Catalog;
using EbookManager.Repositories;

namespace EbookManager.BackOffice.Controllers
{
    [RoutePrefix("catalog")]
    public class AdminCatalogController : Controller
    {
        [HttpGet]
        [Route("")]
        public async Task<ActionResult> Index()
        {
            using (var db = new EbookManagerDbContext())
            {
                var catalogRepository = new CatalogRepository(db);
                var ebooks = await catalogRepository.LoadCatalogAsync();

                var model = new AdminCatalogModel();
                model.Ebooks = ebooks.Select(e => EbookViewModel.FromEbook(e)).ToList();

                return View(model);
            }
        }

        [HttpGet]
        [Route("new-ebook")]
        public ActionResult Add()
        {
            var model = new AddEbookModel();
            return View(model);
        }

        [HttpPost]
        [Route("new-ebook")]
        public async Task<ActionResult> Add(AddEbookModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            using (var db = new EbookManagerDbContext())
            {
                var catalogRepository = new CatalogRepository(db);
                var ebook = new Ebook();
                ebook.Id = Guid.NewGuid();
                ebook.Summary = model.Summary;
                ebook.Title = model.Title;

                ebook.Thumbnail = new byte[model.Thumbnail.ContentLength];
                model.Thumbnail.InputStream.Read(ebook.Thumbnail, 0, ebook.Thumbnail.Length);

                try
                {
                    await catalogRepository.AddEbookAsync(ebook);
                    return RedirectToRoute("editEbook", new { ebookId = ebook.Id });
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("InsertError", e);
                    return View(model);
                }
            }
        }

        [HttpGet]
        [Route("edit-ebook/{ebookId}", Name = "editEbook")]
        public async Task<ActionResult> EditEBook(Guid ebookId)
        {
            using (var db = new EbookManagerDbContext())
            {
                var catalogRepository = new CatalogRepository(db);
                var ebook = await catalogRepository.GetEbookAsync(ebookId);

                if (ebook == null)
                    throw new HttpException(404, "not found");

                var model = new EditEbookModel();
                model.Id = ebook.Id;
                model.Summary = ebook.Summary;
                model.Base64Thumbnail = Convert.ToBase64String(ebook.Thumbnail);
                model.Title = ebook.Title;
                model.PartsCount = ebook.Parts.Count;

                foreach (var part in ebook.Parts)
                {
                    model.ExistingParts.Add(EbookPartViewModel.FromEbookPart(part));
                }

                return View(model);
            }
        }

        [HttpPost]
        [Route("edit-ebook")]
        public async Task<ActionResult> EditEBook(EditEbookModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            using (var db = new EbookManagerDbContext())
            {
                var catalogRepository = new CatalogRepository(db);
                var ebook = await catalogRepository.GetEbookAsync(model.Id);

                if (ebook == null)
                    throw new HttpException(404, "not found");

                ebook.Title = model.Title;
                ebook.Summary = model.Summary;

                if (model.Thumbnail != null)
                {
                    ebook.Thumbnail = new byte[model.Thumbnail.ContentLength];
                    model.Thumbnail.InputStream.Read(ebook.Thumbnail, 0, ebook.Thumbnail.Length);
                }

                if (model.Parts != null)
                {
                    foreach (var part in model.Parts)
                    {
                        if (part == null)
                            continue;

                        var ebookPart = new EbookPart();
                        ebookPart.EbookId = ebook.Id;
                        ebookPart.PartContent = new byte[part.ContentLength];
                        part.InputStream.Read(ebookPart.PartContent, 0, ebookPart.PartContent.Length);
                        ebookPart.Position = ebook.Parts.Count;
                        ebookPart.ContentType = part.ContentType;
                        ebookPart.FileName = System.IO.Path.GetFileName(part.FileName);

                        ebook.Parts.Add(ebookPart);
                    }
                }

                await catalogRepository.UpdateBookAsync(ebook);

                TempData["Success"] = "L'eBook a été sauvegardé";
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        [Route("delete-ebook/{ebookId}", Name = "deleteEbook")]
        public async Task<ActionResult> DeleteBook(Guid ebookId)
        {
            using (var db = new EbookManagerDbContext())
            {
                var catalogRepository = new CatalogRepository(db);
                var ebook = await catalogRepository.GetEbookAsync(ebookId);

                if (ebook == null)
                    throw new HttpException(404, "not found");

                var model = EbookViewModel.FromEbook(ebook);
                return View(model);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("delete-ebook/{ebookId}", Name = "confirmDeleteEbook")]
        public async Task<ActionResult> ConfirmDelete(Guid ebookId)
        {
            using (var db = new EbookManagerDbContext())
            {
                var catalogRepository = new CatalogRepository(db);
                await catalogRepository.DeleteEbookAsync(ebookId);

                TempData["Success"] = "L'eBook a été supprimé";
                return RedirectToAction("Index");
            }
        }
    }
}

EbookManager.BackOffice/Views/AdminCatalog/Add.cshtml
@model EbookManager.BackOffice.Models.AddEbookModel

@{
    ViewBag.Title = "Ajouter un ebook";
}

<h2>@ViewBag.Title</h2>
<hr />

@using (Html.BeginForm("Add", "AdminCatalog", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="row form-group col-lg-12">
        @Html.LabelFor(m => m.Title)
        @Html.TextBoxFor(m => m.Title, new { @class = "form-control input-lg" })
        @Html.ValidationMessageFor(m => m.Title)
    </div>

    <div class="row form-group col-lg-12">
        @Html.LabelFor(m => m.Summary)
        @Html.TextAreaFor(m => m.Summary, new { @class = "form-control input-lg", rows = 10 })
        @Html.ValidationMessageFor(m => m.Summary)
    </div>

    <div class="row form-group col-lg-12">
        @Html.LabelFor(m => m.Thumbnail)
        <input type="file" name="@Html.NameFor(m => m.Thumbnail)" class="form-control" />
        @Html.ValidationMessageFor(m => m.Thumbnail)
    </div>

    <div class="row form-group col-lg-12">
        <input type="submit" value="Sauvegarder" class="btn btn-primary" />
    </div>
}

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

EbookManager.BackOffice/Views/AdminCatalog/DeleteBook.cshtml
@model EbookManager.CommonViewModels.EbookViewModel

@{
    ViewBag.Title = "Suppression d'un ebook";
}

<h2>@ViewBag.Title</h2>

<h3>Voulez-vous vraiment supprimer cet e-book ?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Summary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Summary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PartsCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PartsCount)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Supprimer" class="btn btn-default" /> |
            @Html.ActionLink("Retour", "Index")
        </div>
    }
</div>

EbookManager.BackOffice/Views/AdminCatalog/EditEBook.cshtml
@model EbookManager.BackOffice.Models.EditEbookModel

@{
    ViewBag.Title = "Edition d'un eBook";
}

<h2>@ViewBag.Title</h2>
<hr />

@using (Html.BeginForm("EditEBook", "AdminCatalog", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(m => m.Id)

    <div class="row" style="margin: 5px">
        <div class="col-lg-6">
            <div class="row form-group">
                @Html.LabelFor(m => m.Title)
                @Html.TextBoxFor(m => m.Title, new { @class = "form-control input-lg" })
                @Html.ValidationMessageFor(m => m.Title)
            </div>

            <div class="row form-group">
                @Html.LabelFor(m => m.Summary)
                @Html.TextAreaFor(m => m.Summary, new { @class = "form-control input-lg", rows = 10 })
                @Html.ValidationMessageFor(m => m.Summary)
            </div>

            <div class="row">
                <img src="data:image/png;base64,@Model.Base64Thumbnail" style="max-width: 100px" />
            </div>

            <div class="row form-group">
                @Html.LabelFor(m => m.Thumbnail)
                <input type="file" name="@Html.NameFor(m => m.Thumbnail)" class="form-control" />
                @Html.ValidationMessageFor(m => m.Thumbnail)
            </div>
        </div>
        <div class="col-lg-6">
            @Html.LabelFor(m => m.Parts)
            <p>Il y @Model.PartsCount partie(s) enregistrée(s) pour ce livre</p>
            
            <ul>
                @foreach (var part in Model.ExistingParts)
                {
                    <li><a href="@Url.Content(string.Format("~/EbookPartFileHandler.axd?ebook={0}&position={1}", part.EbookId, part.Position))">@part.FileName</a></li>
                }
            </ul>

            <p><button class="btn" id="btnAddPart">Ajouter une partie</button></p>
            <div id="parts">
                
            </div>
        </div>
    </div>
    <div class="row">
        <input type="submit" value="Sauvegarder" class="btn btn-primary pull-right" />
    </div>
}

@section scripts{
    <script type="text/javascript">
        $(document).ready(function() {
            $("#btnAddPart").click(function (e) {
                e.preventDefault();
                $("#parts").append("<div class='row'><input type='file' class='form-control' style='margin:5px; margin-left:15px;' name='@Html.NameFor(m => m.Parts)' /></div>");
            });
        });
    </script>
}

EbookManager.BackOffice/Views/AdminCatalog/Index.cshtml
@model EbookManager.BackOffice.Models.AdminCatalogModel

@{
    ViewBag.Title = "Administration du catalogue";
}

<h2>@ViewBag.Title</h2>
<hr />

<div class="row col-lg-12">
    @Html.ActionLink("Ajouter un Ebook", "Add", "AdminCatalog", null, new { @class = "btn btn-primary" })
</div>

<div class="row col-lg-12" style="margin-top: 30px;">
    @if (!Model.Ebooks.Any())
    {
        <div class="alert alert-info">
            <strong>Ooops</strong>
            <p>Le catalogue est vide</p>
        </div>
    }
    else
    {
        <table style="width: 100%">
            <thead>
                <tr>
                    <th>Titre</th>
                    <th>Résumé</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var book in Model.Ebooks)
                {
                    <tr>
                        <td>@book.Title</td>
                        <td>@book.Summary</td>
                        <td>@Html.RouteLink("Editer", "editEbook", new { ebookId = book.Id }) - @Html.RouteLink("Supprimer", "deleteEbook", new { ebookId = book.Id })</td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>